### ISSUE TITLE
velotity tools  3.1 example can't be running in smat-servlet

### ISSUE THREAD

**Issue by zzsczz** [smartboot/smart-servlet#2]
I build velocity-tools v3.1 and run it's example form embeded jetty by mvn ,   "mvn   cargo:run"

i copy the war to smat-servlet v0.1.9's  webapps dir (  use "mvn package to get the war"), faied to start the app ,the log is 

开始解压[velocity-tools-examples-showcase-3.1.war]...
java.lang.IllegalArgumentException: illegal mapping : nolayout/*

[velocity-tools-examples-showcase.tar.gz](https://github.com/smartboot/smart-servlet/files/11412306/velocity-tools-examples-showcase.tar.gz)

**Comment by smthing** [comment]
<img width="482" alt="image" src="https://user-images.githubusercontent.com/6135303/236624859-486e856c-9a25-4bea-8038-e7589ad70903.png">
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/6135303/236624858-2631ffc9-1b74-4c83-83fe-f4259d0bbcef.png">

**Comment by zzsczz** [comment]
thanks [smthing](https://github.com/smthing)

thesmart-selvet  start modified web.xml, but most demos can't work well. 

tomcat  start modified web.xml and demos works well.

Java is write once and debug anywell. The api specification  will not  never cover every conner of all the code.

**Comment by zzsczz** [comment]
the index page is http://127.0.0.1:8080/velocity-tools-examples-showcase-3.1/toolmenu.vm

or 

http://127.0.0.1:8080/velocity-tools-examples-showcase-3.2-SNAPSHOT/toolmenu.vm
(build form the latest source)

**Comment by smthing** [comment]
![image](https://user-images.githubusercontent.com/6135303/236670565-718cf5ab-bb2e-4c48-997d-9729b6e3721a.png)
我这边显示正常，你可以试试我下面这个zip包。
我仅仅是将`<url-pattern>nolayout/*</url-pattern>`调整成`<url-pattern>/nolayout/*</url-pattern>`
并在pom.xml中加入了
```
<plugin>
        <groupId>org.smartboot.servlet</groupId>
        <artifactId>smart-servlet-maven-plugin</artifactId>
        <version>0.1.9</version><!--最新版本 -->
        <configuration>
          <port>8080</port>
          <path>/velocity-tools-examples-showcase-3.1</path>
        </configuration>
</plugin>
```
[velocity-tools-examples-showcase.zip](https://github.com/smartboot/smart-servlet/files/11414501/velocity-tools-examples-showcase.zip)

**Comment by smthing** [comment]
我尝试过用tomcat启动你的工程，也是会因为url-pattern非法导致启动失败的
![image](https://user-images.githubusercontent.com/6135303/236672129-95f79522-b5c6-4893-831b-48ecc9b9be11.png)

**Comment by zzsczz** [comment]
choose  the first  AlternatorTool item

<img width="1126" alt="p1" src="https://user-images.githubusercontent.com/22384100/236672198-becd489a-ce16-4686-8401-e1baa51f9c57.png">

click the go

<img width="992" alt="p2" src="https://user-images.githubusercontent.com/22384100/236672212-124ea82b-e9d9-425f-bb95-99c6265452c1.png">

tomcat works well

弯弯角角太多了

**Comment by zzsczz** [comment]
规范 到 工程之间 有距离

**Comment by smthing** [comment]
找到原因了，是提取端口号的时候下标存在偏差。会在0.2版本中修复一下。
ps://方便告知下你是哪里人吗？我不太会用英语进行回复。

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/6135303/236675322-6de61511-37e6-4318-a6f5-f490fb9341b1.png">

**Comment by zzsczz** [comment]
湖北人，在魔都

**Comment by smthing** [comment]
😓
你可以先试试 0.2-SNAPSHOT，没啥问题的话我近期发个版本。
可以参考：[https://smartboot.tech/smart-servlet/quickstart.html](https://smartboot.tech/smart-servlet/quickstart.html) 中的Maven插件

**Comment by zzsczz** [comment]
mvn package smart-servlet:run    润不起来



[apsbyoptaplanner.zip](https://github.com/smartboot/smart-servlet/files/11415349/apsbyoptaplanner.zip)


<img width="1277" alt="maven" src="https://user-images.githubusercontent.com/22384100/236686791-b50c39e3-6339-4a69-9c46-2d3933e8ba74.png">

**Comment by smthing** [comment]
可能是你的配置不支持拉取快照包吧。
正式包 0.2.1 已经发布了，你也可以从[https://gitee.com/smartboot/smart-servlet/releases/tag/v0.2.1](https://gitee.com/smartboot/smart-servlet/releases/tag/v0.2.1)下载程序包。
