### ISSUE TITLE
集成springboot 启动后报错Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.

### ISSUE THREAD

**Issue by l1p1p3088** [smartboot/smart-servlet#6]
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-tomcat</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>tech.smartboot.servlet</groupId>
            <artifactId>smart-servlet-spring-boot-starter</artifactId>
            <version>2.4</version>
        </dependency>

**Comment by smthing** [comment]
springboot版本是多少

**Comment by l1p1p3088** [comment]
2.2.2

**Comment by smthing** [comment]
smart-servlet适配的是springboot3
